name: "Test"
"on":
    pull_request: null
    push: null
    workflow_dispatch: null
permissions:
    contents: "write"
jobs:
    macos:
        runs-on: "macos-latest"
        name: "macOS Tests"
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4"
              with:
                  submodules: true
            - name: "Setup Xcode version"
              uses: "maxim-lobanov/setup-xcode@v1.6.0"
              with:
                  xcode-version: "16.3"
            - name: "Log Swift version"
              run: "swift --version"
            - name: "Run Tests"
              run: "swift test"
